version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - nestjs-network

  nestjs:
    build: .
    container_name: nestjs-container
    ports:
      - "3030:3000"
    depends_on:
      - mysql
    networks:
      - nestjs-network
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_DATABASE: ${MYSQL_DATABASE}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin-container
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "8080:80"
    networks:
      - nestjs-network
    depends_on:
      - mysql
  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    ports:
      - "1025:1025"   # SMTP port (pour envoyer les e-mails)
      - "8025:8025"   # Web interface (pour visualiser les e-mails capturés)
    environment:
      - MH_STORAGE=maildir
    restart: unless-stopped
    networks:
      - nestjs-network

volumes:
  mysql_data:

networks:
  nestjs-network:
    driver: bridge
